export const COMMON_MEDICINES = [
  { name: 'Paracétamol', dosages: ['500mg 3x/j', '1g 3x/j', '250mg 2x/j'] },
  { name: 'Artéméther-Luméfantrine (Coartem)', dosages: ['4 comprimés 2x/j (3j)', '3 comprimés 2x/j (3j)', '2 comprimés 2x/j (3j)'] },
  { name: 'Amoxicilline', dosages: ['500mg 3x/j', '1g 2x/j', '250mg 3x/j'] },
  { name: 'Amoxicilline-Acide Clavulanique', dosages: ['500mg/62.5mg 3x/j', '1g/125mg 2x/j'] },
  { name: 'Azithromycine', dosages: ['500mg 1x/j (3j)', '250mg 1x/j (3j)'] },
  { name: 'Ciprofloxacine', dosages: ['500mg 2x/j', '250mg 2x/j'] },
  { name: 'Métronidazole', dosages: ['500mg 3x/j', '250mg 3x/j'] },
  { name: 'Ceftriaxone', dosages: ['1g IM 1x/j', '2g IV 1x/j'] },
  { name: 'Doxycycline', dosages: ['100mg 1x/j', '200mg 1x/j'] },
  { name: 'Ibuprofène', dosages: ['400mg 3x/j', '600mg 2x/j', '200mg 3x/j'] },
  { name: 'Amlodipine', dosages: ['5mg 1x/j', '10mg 1x/j'] },
  { name: 'Enalapril', dosages: ['5mg 1x/j', '10mg 1x/j', '20mg 1x/j'] },
  { name: 'Metformine', dosages: ['500mg 2x/j', '850mg 2x/j', '1000mg 2x/j'] },
  { name: 'Salbutamol (Aérosol)', dosages: ['2 bouffées 4x/j si besoin', '1 bouffée 4x/j si besoin'] },
  { name: 'Oméprazole', dosages: ['20mg 1x/j', '40mg 1x/j'] },
  { name: 'Prednisolone', dosages: ['40mg 1x/j', '20mg 1x/j', '10mg 1x/j'] },
  { name: 'Fer + Acide Folique', dosages: ['1 comprimé 1x/j', '1 comprimé 2x/j'] },
  { name: 'Albendazole', dosages: ['400mg dose unique', '200mg dose unique'] },
  { name: 'Diazépam', dosages: ['5mg 1x/j si besoin', '10mg 1x/j si besoin'] },
  { name: 'Furosémide', dosages: ['40mg 1x/j', '40mg 2x/j'] },
  { name: 'Diclofénac', dosages: ['50mg 2x/j', '75mg IM 1x/j'] },
  { name: 'Vitamine A', dosages: ['200000 UI dose unique', '100000 UI dose unique'] },
  { name: 'Multivitamines', dosages: ['1 comprimé 1x/j', '1 comprimé 2x/j'] },
  { name: 'Smectite', dosages: ['1 sachet 3x/j', '1 sachet 2x/j'] },
  { name: 'Dompéridone', dosages: ['10mg 3x/j', '10mg 2x/j'] },
  { name: 'Quinine', dosages: ['500mg 3x/j', '300mg 3x/j'] },
  { name: 'Artésunate', dosages: ['2.4mg/kg IV J1-J3', '1.2mg/kg IV J1-J3'] },
  { name: 'Nifédipine', dosages: ['10mg 2x/j', '20mg 2x/j'] },
  { name: 'Hydrochlorothiazide', dosages: ['25mg 1x/j', '12.5mg 1x/j'] },
  { name: 'Insuline', dosages: ['Selon protocole'] },
  { name: 'Praziquantel', dosages: ['40mg/kg dose unique', '20mg/kg 2x/j'] },
  { name: 'Captopril', dosages: ['25mg 2x/j', '50mg 2x/j'] },
];

export const COMMON_DIAGNOSES = [
  'Paludisme',
  'Infection respiratoire aiguë',
  'Hypertension artérielle',
  'Diabète de type 2',
  'Diarrhée aiguë',
  'Infection urinaire',
  'Rhumatisme',
  'Dermatose',
  'Anémie',
  'Autre',
];
